SELECT id FROM tags WHERE name = ?;
SELECT * FROM livecomment_reports WHERE livestream_id = ?;
SELECT IFNULL(MAX(tip), 0) FROM livestreams l INNER JOIN livecomments l2 ON l2.livestream_id = l.id WHERE l.id = ?;
SELECT COUNT(*) FROM livestream_viewers_history WHERE livestream_id = ?;
SELECT COUNT(*) FROM users u INNER JOIN livestreams l ON l.user_id = u.id INNER JOIN reactions r ON r.livestream_id = l.id WHERE u.id = ?;
SELECT * FROM tags WHERE id = ?;
SELECT COUNT(*) FROM livestreams l INNER JOIN reactions r ON l.id = r.livestream_id WHERE l.id = ?;
SELECT * FROM users;
SELECT * FROM livestreams WHERE user_id = ?;
SELECT * FROM livestreams;
SELECT COUNT(*) FROM livestreams l INNER JOIN livecomment_reports r ON r.livestream_id = l.id WHERE l.id = ?;
INSERT INTO livecomments (user_id, livestream_id, comment, tip, created_at) VALUES (?);
SELECT * FROM tags;
SELECT * FROM livestream_tags WHERE livestream_id = ?;
SELECT * FROM livecomments WHERE livestream_id = ? ORDER BY created_at DESC LIMIT 1;
INSERT INTO ng_words(user_id, livestream_id, word, created_at) VALUES (?);
DELETE FROM livestream_viewers_history WHERE user_id = ? AND livestream_id = ?;
SELECT * FROM livestreams ORDER BY id DESC LIMIT 50;
SELECT * FROM livecomments;
SELECT IFNULL(SUM(l2.tip), 0) FROM users u INNER JOIN livestreams l ON l.user_id = u.id INNER JOIN livecomments l2 ON l2.livestream_id = l.id WHERE u.id = ?;
SELECT * FROM livestream_tags WHERE tag_id IN (?) ORDER BY livestream_id DESC;
DELETE FROM livecomments WHERE id = ? AND livestream_id = ? AND (SELECT COUNT(*) FROM (SELECT ? AS text) AS texts INNER JOIN (SELECT CONCAT('%', ?, '%') AS pattern) AS patterns ON texts.text LIKE patterns.pattern) >= 1;
SELECT COUNT(*) FROM (SELECT ? AS text) AS texts INNER JOIN (SELECT CONCAT('%', ?, '%') AS pattern) AS patterns ON texts.text LIKE patterns.pattern;
INSERT INTO livestream_tags (livestream_id, tag_id) VALUES (?);
SELECT * FROM reactions WHERE livestream_id = ? ORDER BY created_at DESC;
SELECT * FROM users WHERE id = ?;
SELECT image FROM icons WHERE user_id = ?;
INSERT INTO users (name, display_name, description, password) VALUES (?);
SELECT IFNULL(SUM(tip), 0) FROM livecomments;
INSERT INTO livestreams (user_id, title, description, playlist_url, thumbnail_url, start_at, end_at) VALUES (?);
INSERT INTO livestream_viewers_history (user_id, livestream_id, created_at) VALUES (?);
INSERT INTO reactions (user_id, livestream_id, emoji_name, created_at) VALUES (?);
SELECT * FROM livecomments WHERE id = ?;
DELETE FROM icons WHERE user_id = ?;
SELECT * FROM livecomments WHERE livestream_id = ? ORDER BY created_at DESC LIMIT 10;
SELECT slot FROM reservation_slots WHERE start_at = ? AND end_at = ?;
SELECT * FROM reservation_slots WHERE start_at >= ? AND end_at <= ? FOR UPDATE;
SELECT * FROM reactions WHERE livestream_id = ? ORDER BY created_at DESC LIMIT 10;
SELECT * FROM users WHERE name = ?;
SELECT * FROM livestreams WHERE id = ?;
SELECT IFNULL(SUM(l2.tip), 0) FROM livestreams l INNER JOIN livecomments l2 ON l.id = l2.livestream_id WHERE l.id = ?;
SELECT id, user_id, livestream_id, word FROM ng_words WHERE user_id = ? AND livestream_id = ?;
SELECT * FROM livecomments WHERE livestream_id = ? ORDER BY created_at DESC;
UPDATE reservation_slots SET slot = slot - 1 WHERE start_at >= ? AND end_at <= ?;
SELECT COUNT(*) FROM users u INNER JOIN livestreams l ON l.user_id = u.id INNER JOIN reactions r ON r.livestream_id = l.id WHERE u.name = ?;
SELECT * FROM ng_words WHERE user_id = ? AND livestream_id = ? ORDER BY created_at DESC;
INSERT INTO livecomment_reports(user_id, livestream_id, livecomment_id, created_at) VALUES (?);
SELECT * FROM livecomments WHERE livestream_id = ?;
SELECT r.emoji_name FROM users u INNER JOIN livestreams l ON l.user_id = u.id INNER JOIN reactions r ON r.livestream_id = l.id WHERE u.name = ? GROUP BY emoji_name ORDER BY COUNT(*) DESC, emoji_name DESC LIMIT 1;
SELECT * FROM livestreams WHERE id = ? AND user_id = ?;
SELECT * FROM themes WHERE user_id = ?;
SELECT id FROM users WHERE name = ?;
INSERT INTO themes (user_id, dark_mode) VALUES (?);
SELECT COUNT(*) FROM livestreams l INNER JOIN reactions r ON r.livestream_id = l.id WHERE l.id = ?;
INSERT INTO icons (user_id, image) VALUES (?);
SELECT * FROM ng_words WHERE livestream_id = ?;
SELECT COUNT(*) FROM livestreams l INNER JOIN livestream_viewers_history h ON h.livestream_id = l.id WHERE l.id = ?;
